name: pf-selenium

services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "4444:4444"   # WebDriver
      - "7900:7900"   # (opcional) VNC web

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./app/frontend:/usr/share/nginx/html:ro
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    build:
      context: ./app/backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pf
      POSTGRES_USER: pf_user
      POSTGRES_PASSWORD: pf_pass
    ports:
      - "5432:5432"
    volumes:
      - pf_db_data:/var/lib/postgresql/data

volumes:
  pf_db_data:
