server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/pf
    username: pf_user
    password: pf_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
